// Texts.swift
// onlineSHop_TestTask. Created by Zlata Guseva.

enum Texts {
    static let homeTitle = "Trade by bata"
    static let viewAll = "View all"
    static let searchBarPlaceholder = "What are you loking for?"
    static let location = "Location"
    static let soon = "SOON"
    static let latest = "Latest"
    static let flashSale = "Flash Sale"
    static let phones = "Phones"
    static let headphones = "Headphones"
    static let games = "Games"
    static let cars = "Cars"
    static let furniture = "Furniture"
    static let kids = "Kids"
    static let profile = "Profile"
    static let changePhoto = "Change photo"
    static let profileName = "Satria Adhi Pradana"
    static let uploadItem = "Upload item"
    static let tradeStore = "Trade store"
    static let paymentMethod = "Payment method"
    static let balance = "Balance"
    static let tradeHistory = "Trade history"
    static let restorePurchase = "Restore Purchase"
    static let help = "Help"
    static let logOut = "Log out"
    static let welcome = "Welcome back"
    static let email = "E-mail"
    static let password = "Password"
    static let haveNoAccount = "Still have no account? Sign in"
    static let login = "Login"
    static let signIn = "Sign In"
    static let firstName = "First name"
    static let lastName = "Last name"
    static let haveAccount = "Already have an account? Log in"
    static let withApple = "Sign in with Apple"
    static let withGoogle = "Sign in with Google"
    static let userExist = "This user already exist"
    static let wrongEmail = "Something wrong with your email"
    static let noUser = "There is no user with this email"
    static let wrongPassword = "Wrong password"
    static let enterPassword = "Please enter password"
    static let enterEmail = "Please enter e-mail"
}
